export interface StageDefinition {
  order: number
  name: string
  nameEn: string
  description: string
  icon: string
  items: StageItemDefinition[]
}

export interface StageItemDefinition {
  code: string
  category: string
  name: string
  standard: string
  responsible: string
  photoRequired: boolean
  clientConfirmationRequired: boolean
}

export const STAGE_DEFINITIONS: StageDefinition[] = [
  {
    order: 1,
    name: '需求沟通与现场勘察',
    nameEn: 'Consultation & Survey',
    description: '全面了解业主生活方式、审美偏好与功能需求，完成现场精确测量',
    icon: 'MessageSquare',
    items: [
      { code: '1.1', category: '需求访谈', name: '家庭成员构成与生活习惯梳理', standard: '填写《生活方式问卷》', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '1.2', category: '需求访谈', name: '功能空间需求确认', standard: '逐房间确认功能定位', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '1.3', category: '需求访谈', name: '风格偏好与审美参考', standard: '提供参考案例≥3组', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '1.4', category: '需求访谈', name: '预算范围沟通', standard: '明确预算区间与优先级', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '1.5', category: '需求访谈', name: '特殊需求登记', standard: '老人/儿童/宠物/收藏等', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '1.6', category: '现场勘察', name: '原始结构精确测量', standard: '激光测距仪，误差≤3mm', responsible: '深化设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '1.7', category: '现场勘察', name: '现有管线位置标注', standard: '标注给水/排水/燃气/强弱电', responsible: '深化设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '1.8', category: '现场勘察', name: '承重结构确认', standard: '标注承重墙/梁/柱位置', responsible: '深化设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '1.9', category: '现场勘察', name: '门窗尺寸及开启方式', standard: '含窗台高度、开启方向', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '1.10', category: '现场勘察', name: '现场照片存档', standard: '每房间≥4角度，编号存档', responsible: '深化设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '1.11', category: '现场勘察', name: '物业限制条件确认', standard: '装修时间/电梯使用/垃圾清运', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
    ],
  },
  {
    order: 2,
    name: '概念方案设计',
    nameEn: 'Concept Design',
    description: '输出整体空间规划方案，确定设计方向与风格基调',
    icon: 'Palette',
    items: [
      { code: '2.1', category: '方案设计', name: '平面布局方案', standard: '≥2套方案供比选', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '2.2', category: '方案设计', name: '动线分析', standard: '生活动线/家务动线/访客动线', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '2.3', category: '方案设计', name: '空间功能分区', standard: '标注每个区域功能定位', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '2.4', category: '方案设计', name: '风格意向板', standard: '材质/色彩/质感定调', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '2.5', category: '方案设计', name: '重点空间效果表达', standard: '客厅/主卧/厨房等核心空间', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '2.6', category: '方案设计', name: '方案汇报与确认', standard: '业主签字确认最终方案', responsible: '设计师', photoRequired: false, clientConfirmationRequired: true },
    ],
  },
  {
    order: 3,
    name: '深化设计与施工图',
    nameEn: 'Detail Design',
    description: '将概念方案转化为可落地的全套施工图纸',
    icon: 'Ruler',
    items: [
      { code: '3.1', category: '施工图', name: '墙体拆改图', standard: '标注拆除/新建墙体位置及材质', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.2', category: '施工图', name: '平面布置图（定稿）', standard: '家具尺寸定位到毫米', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.3', category: '施工图', name: '天花布置图', standard: '吊顶造型/标高/灯位', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.4', category: '施工图', name: '地面铺装图', standard: '材质分区/排砖方案/收口', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.5', category: '施工图', name: '给排水点位图', standard: '冷热水点位/排水预留', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.6', category: '施工图', name: '强弱电点位图', standard: '插座/开关/网络/智能面板', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.7', category: '施工图', name: '暖通布置图', standard: '风机盘管/地暖分区/新风管路', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.8', category: '施工图', name: '立面展开图', standard: '每面墙体立面详图', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.9', category: '施工图', name: '节点大样图', standard: '关键收口/转角/造型节点', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.10', category: '施工图', name: '全屋定制拆单图', standard: '柜体结构/五金/内部分格', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.11', category: '图纸审核', name: '设计师自审', standard: '核对方案意图与施工可行性', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.12', category: '图纸审核', name: '项目经理施工审图', standard: '核对施工可行性与工艺衔接', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '3.13', category: '图纸审核', name: '业主图纸确认', standard: '逐张讲解，签字确认', responsible: '设计师', photoRequired: false, clientConfirmationRequired: true },
    ],
  },
  {
    order: 4,
    name: '材料确认与采购',
    nameEn: 'Material Selection',
    description: '确定全部材料选型，透明报价，锁定供应商',
    icon: 'Package',
    items: [
      { code: '4.1', category: '材料选型', name: '基础辅材清单确认', standard: '水管/电线/防水/板材等品牌锁定', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: true },
      { code: '4.2', category: '材料选型', name: '主材选型确认', standard: '瓷砖/石材/木地板/卫浴洁具', responsible: '设计师', photoRequired: false, clientConfirmationRequired: true },
      { code: '4.3', category: '材料选型', name: '五金配件清单', standard: '铰链/滑轨/拉手/地漏等', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '4.4', category: '材料选型', name: '暖通设备选型', standard: '空调/地暖/新风品牌及型号', responsible: '设计师', photoRequired: false, clientConfirmationRequired: true },
      { code: '4.5', category: '材料选型', name: '智能设备选型', standard: '智能面板/窗帘电机/传感器', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '4.6', category: '材料选型', name: '灯具清单', standard: '型号/色温/功率/安装方式', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '4.7', category: '报价采购', name: '材料明细报价单输出', standard: '品牌/型号/单价/数量/小计', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '4.8', category: '报价采购', name: '业主确认报价', standard: '签字确认，可自行比价', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: true },
      { code: '4.9', category: '报价采购', name: '材料下单与交期确认', standard: '确认到场时间，匹配施工进度', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '4.10', category: '报价采购', name: '材料到场验收', standard: '核对品牌/型号/数量/外观', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
    ],
  },
  {
    order: 5,
    name: '施工准备',
    nameEn: 'Pre-Construction',
    description: '完成开工前全部准备工作，确保施工有序启动',
    icon: 'ClipboardList',
    items: [
      { code: '5.1', category: '开工准备', name: '物业开工手续办理', standard: '装修申请/押金/施工证', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '5.2', category: '开工准备', name: '施工班组交底会', standard: '全套图纸技术交底', responsible: '设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '5.3', category: '开工准备', name: '工艺标准培训', standard: '核心节点工艺卡逐项讲解', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '5.4', category: '开工准备', name: '施工进度计划表', standard: '各工种进退场时间节点', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: true },
      { code: '5.5', category: '开工准备', name: '现场保护', standard: '入户门/电梯/公共区域保护', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '5.6', category: '开工准备', name: '临时水电接驳', standard: '确认施工用水用电', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
    ],
  },
  {
    order: 6,
    name: '基础施工（水电/防水）',
    nameEn: 'MEP & Waterproofing',
    description: '完成隐蔽工程，此阶段为质量生命线，验收标准最严格',
    icon: 'Zap',
    items: [
      { code: '6.1', category: '墙体改造', name: '拆除墙体复核', standard: '与图纸核对，确认非承重墙', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.2', category: '墙体改造', name: '新建墙体施工', standard: '砌体材质/拉结筋/顶部斜砌', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.3', category: '墙体改造', name: '墙体验收', standard: '垂直度≤3mm/m，平整度≤4mm/m', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.4', category: '水电预埋', name: '给水管路布管', standard: '走顶为主，横平竖直，管卡间距≤60cm', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.5', category: '水电预埋', name: '给水打压测试', standard: '0.8MPa保压30min，压降≤0.05MPa', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.6', category: '水电预埋', name: '排水管路安装', standard: '坡度≥1%，存水弯/检修口预留', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.7', category: '水电预埋', name: '排水通水测试', standard: '全部排水点通水，无堵漏', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.8', category: '水电预埋', name: '强电线路布管', standard: '线管分色，强弱电间距≥20cm', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.9', category: '水电预埋', name: '弱电线路布管', standard: '网络/电话/电视/智能预埋', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.10', category: '水电预埋', name: '水电定位复核', standard: '实际点位与图纸逐一核对', responsible: '深化设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.11', category: '水电预埋', name: '水电隐蔽验收', standard: '拍照存档，业主签字确认', responsible: '设计师', photoRequired: true, clientConfirmationRequired: true },
      { code: '6.12', category: '防水工程', name: '基层处理', standard: '清理浮灰，阴角圆弧处理R≥30mm', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.13', category: '防水工程', name: '第一遍防水涂刷', standard: '东方雨虹/德高，涂刷均匀无遗漏', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.14', category: '防水工程', name: '第二遍防水涂刷', standard: '与第一遍垂直交叉，总厚度≥1.5mm', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.15', category: '防水工程', name: '闭水试验', standard: '蓄水48小时，楼下无渗漏', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '6.16', category: '防水工程', name: '防水验收', standard: '拍照存档，业主签字确认', responsible: '设计师', photoRequired: true, clientConfirmationRequired: true },
    ],
  },
  {
    order: 7,
    name: '主体施工（瓦工/木作/暖通）',
    nameEn: 'Structure & HVAC',
    description: '完成空间主体结构，此阶段决定空间最终比例与质感',
    icon: 'Hammer',
    items: [
      { code: '7.1', category: '瓦工工程', name: '排砖方案审核', standard: '设计师确认排砖方案后施工', responsible: '设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '7.2', category: '瓦工工程', name: '墙砖铺贴', standard: '薄贴法，空鼓率≤3%', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '7.3', category: '瓦工工程', name: '地砖铺贴', standard: '平整度≤2mm/2m，缝宽均匀', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '7.4', category: '瓦工工程', name: '阳角处理', standard: '45°对缝或阳角条，线条顺直', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '7.5', category: '瓦工工程', name: '瓦工验收', standard: '空鼓检测/平整度/缝宽/阴阳角', responsible: '设计师', photoRequired: true, clientConfirmationRequired: true },
      { code: '7.6', category: '暖通工程', name: '中央空调安装', standard: '室内机定位/冷媒管/冷凝水管', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '7.7', category: '暖通工程', name: '地暖盘管（如有）', standard: '管间距/分集水器/保温层', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '7.8', category: '暖通工程', name: '新风系统安装', standard: '管路走向/风口定位/过滤等级', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '7.9', category: '暖通工程', name: '暖通打压测试', standard: '按设备要求打压，记录数据', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '7.10', category: '暖通工程', name: '暖通验收', standard: '拍照存档，签字确认', responsible: '设计师', photoRequired: true, clientConfirmationRequired: true },
      { code: '7.11', category: '木工吊顶', name: '吊顶龙骨安装', standard: '轻钢龙骨间距≤40cm，吊杆间距≤1m', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '7.12', category: '木工吊顶', name: '吊顶封板', standard: '石膏板错缝拼接，预留检修口', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '7.13', category: '木工吊顶', name: '造型基层制作', standard: '与图纸核对尺寸/弧度/标高', responsible: '深化设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '7.14', category: '木工吊顶', name: '木工验收', standard: '牢固度/平整度/尺寸准确性', responsible: '设计师', photoRequired: true, clientConfirmationRequired: true },
    ],
  },
  {
    order: 8,
    name: '面层施工（油漆/墙面/安装）',
    nameEn: 'Finishing & Installation',
    description: '完成空间视觉呈现，此阶段直接决定交付观感',
    icon: 'Paintbrush',
    items: [
      { code: '8.1', category: '墙面工程', name: '基层处理', standard: '挂网/找平/容差≤3mm/2m', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '8.2', category: '墙面工程', name: '腻子批刮', standard: '≥2遍，干透后打磨', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '8.3', category: '墙面工程', name: '底漆涂刷', standard: '均匀覆盖，无遗漏', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '8.4', category: '墙面工程', name: '面漆涂刷', standard: '≥2遍，施工温度5-35°C，湿度≤85%', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '8.5', category: '墙面工程', name: '墙面验收', standard: '色差/流挂/开裂/平整度检查', responsible: '设计师', photoRequired: true, clientConfirmationRequired: true },
      { code: '8.6', category: '安装工程', name: '开关面板安装', standard: '与墙面齐平，接线正确', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '8.7', category: '安装工程', name: '灯具安装', standard: '核对型号/位置/色温', responsible: '深化设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '8.8', category: '安装工程', name: '卫浴洁具安装', standard: '排水通畅/密封良好', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '8.9', category: '安装工程', name: '五金挂件安装', standard: '位置准确/固定牢靠', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '8.10', category: '安装工程', name: '木门安装', standard: '开关顺畅/缝隙均匀/锁具灵活', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '8.11', category: '安装工程', name: '安装工程验收', standard: '逐项功能测试', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: true },
    ],
  },
  {
    order: 9,
    name: '全屋定制与软装',
    nameEn: 'Custom & Furnishing',
    description: '定制家具安装到位，软装陈设完成空间最终呈现',
    icon: 'Sofa',
    items: [
      { code: '9.1', category: '全屋定制', name: '柜体到场验收', standard: '核对图纸/板材/五金/数量', responsible: '深化设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '9.2', category: '全屋定制', name: '柜体安装', standard: '与墙面收口严密，水平垂直', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '9.3', category: '全屋定制', name: '门板/台面安装', standard: '色差/缝隙/开关手感', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '9.4', category: '全屋定制', name: '定制验收', standard: '功能测试/收口质量/成品保护', responsible: '设计师', photoRequired: true, clientConfirmationRequired: true },
      { code: '9.5', category: '软装陈设', name: '家具到场与摆放', standard: '核对款式/尺寸/颜色', responsible: '设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '9.6', category: '软装陈设', name: '窗帘安装', standard: '轨道/面料/长度/垂感', responsible: '设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '9.7', category: '软装陈设', name: '饰品/挂画/绿植', standard: '按设计方案定位摆放', responsible: '设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '9.8', category: '软装陈设', name: '软装整体效果确认', standard: '设计师现场调整至最终状态', responsible: '设计师', photoRequired: true, clientConfirmationRequired: true },
    ],
  },
  {
    order: 10,
    name: '竣工验收与交付',
    nameEn: 'Final Inspection',
    description: '全面系统验收，确保零遗留问题交付',
    icon: 'CheckCircle',
    items: [
      { code: '10.1', category: '竣工验收', name: '全屋深度保洁', standard: '专业保洁团队，开荒清洁', responsible: '项目经理', photoRequired: true, clientConfirmationRequired: false },
      { code: '10.2', category: '竣工验收', name: '水路系统全检', standard: '逐点开水/排水/检查渗漏', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '10.3', category: '竣工验收', name: '电路系统全检', standard: '逐回路通电/接地/漏保测试', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '10.4', category: '竣工验收', name: '暖通系统调试', standard: '制冷/制热/新风全功能测试', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '10.5', category: '竣工验收', name: '智能系统调试', standard: '灯光场景/窗帘/传感器联动', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '10.6', category: '竣工验收', name: '设计师终检', standard: '整体效果与设计意图比对', responsible: '设计师', photoRequired: true, clientConfirmationRequired: false },
      { code: '10.7', category: '交付', name: '整改清单处理', standard: '验收发现问题逐项销项', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '10.8', category: '交付', name: '竣工图纸移交', standard: '含水电隐蔽/结构改造等', responsible: '深化设计师', photoRequired: false, clientConfirmationRequired: false },
      { code: '10.9', category: '交付', name: '材料质保卡汇总', standard: '各品牌质保卡/发票整理', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '10.10', category: '交付', name: '使用说明交底', standard: '设备使用/保养/注意事项', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '10.11', category: '交付', name: '竣工验收单签署', standard: '业主签字确认，正式交付', responsible: '设计师', photoRequired: true, clientConfirmationRequired: true },
      { code: '10.12', category: '交付', name: '竣工摄影存档', standard: '专业摄影记录完工效果', responsible: '设计师', photoRequired: true, clientConfirmationRequired: false },
    ],
  },
  {
    order: 11,
    name: '售后服务',
    nameEn: 'After-Sales',
    description: '交付不是终点，持续为业主的居住品质负责',
    icon: 'HeartHandshake',
    items: [
      { code: '11.1', category: '质保服务', name: '1个月回访', standard: '入住体验反馈，细节调整', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '11.2', category: '质保服务', name: '3个月回访', standard: '季节变化后检查（开裂/渗漏）', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '11.3', category: '质保服务', name: '1年回访', standard: '全屋系统性检查', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '11.4', category: '质保服务', name: '隐蔽工程质保', standard: '水电管路5年质保', responsible: '公司', photoRequired: false, clientConfirmationRequired: false },
      { code: '11.5', category: '质保服务', name: '售后响应', standard: '48h内响应，72h内上门', responsible: '项目经理', photoRequired: false, clientConfirmationRequired: false },
      { code: '11.6', category: '质保服务', name: '终身维护支持', standard: '质保期外提供有偿维护服务', responsible: '公司', photoRequired: false, clientConfirmationRequired: false },
    ],
  },
]

export const TOTAL_ITEMS = STAGE_DEFINITIONS.reduce((sum, s) => sum + s.items.length, 0)
